version: "3.9"

services:
  java_app:
    container_name: java_app
    image: demo-java_app:1.0.0
    build:
     context: ./ # Directorio donde se encuentra el Dockerfile de tu aplicación Spring Boot
     dockerfile: Dockerfile # Nombre del archivo Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres #TODO: HIDE IN DOCKER PARAMS
      - DATABASE_PASSWORD=mysecretpassword #TODO: HIDE IN DOCKER PARAMS
    depends_on:
      - postgres_db
      - redis
  postgres_db:
    container_name: java_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres  #TODO: HIDE IN DOCKER PARAMS
      POSTGRES_PASSWORD: mysecretpassword #TODO: HIDE IN  DOCKER PARAMS
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes #TODO: ADD PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL