version: "3.9"

services:
  java_app:
    container_name: java_app
    image: demo-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres #TODO: OCULTAR
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres  #TODO: OCULTAR o borrar duplicado
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    ports:
      - 6379:6379